language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      
    - os: linux
      dist: xenial
      compiler: clang

script:
- mkdir build
- cd build
- cmake ..
- make
