language: cpp
dist: xenial
osx_image: xcode10.1

before_script:
  - mkdir build
  - cd build

matrix:
  include:
    # Linux/GCC Compilation
    - os: linux
      compiler: gcc
      script:
        - make -j
    # Linux/Clang Compilation
    - os: linux
      compiler: clang
      script:
        - make -j
    # OSX/XCode Compilation
    - os: osx
      osx_image: xcode10.1
      script:
        - make -j
    # Windows/MSVC Compilation
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - MSBuild.exe ALL_BUILD.vcxproj -m
