language: cpp
dist: xenial

before_script:
  - mkdir build
  - cd build

matrix:
  include:
    # Linux/GCC Compilation
    - os: linux
      compiler: gcc
      script:
        - cmake ..
        - make -j
    # Linux/Clang Compilation
    - os: linux
      compiler: clang
      script:
        - cmake ..
        - make -j
    # OSX/XCode Compilation
    - os: osx
      osx_image: xcode10.1
      script:
        - cmake ..
        - make -j
    # Windows/MSVC Compilation
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - cmake ..
        - MSBuild.exe ALL_BUILD.vcxproj -m
    # Clang-Tidy check
    - os: linux
      env:
        - TEST="Clang Tidy"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-tidy-7
      script:
        - cmake -DENABLE_CLANG_TIDY=ON ..
        - make
        - make tidy > output.txt
        - |
          if [[ -n $(grep "warning: " output.txt) ]] || [[ -n $(grep "error: " output.txt) ]]; then
            echo "You must pass the clang tidy checks before submitting a pull request"
            echo ""
            grep --color -E '^|warning: |error: ' output.txt
            exit -1;
          else
            echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
          fi
    # Clang-Format check
    - os: linux
      env:
        - TEST="Clang Format"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-format-7
      script:
        - cmake -DENABLE_CLANG_FORMAT=ON ..
        - make
        - make format
        - |
          if [[ -n $(git diff) ]]; then
            echo "You must run make format before submitting a pull request"
            echo ""
            git diff
            exit -1
          fi
